# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: allxiaa
  tag: "v1.0.1-124b4f0"
  arch: amd64
secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN
